version: '3.8'

services:
  network-sentinel:
    build: .
    container_name: wifi-sentinel
    # IMPORTANTE: Usamos 'host' para que el contenedor vea la red real de tu casa
    network_mode: "host"
    restart: unless-stopped
    # Pasamos la URL como variable de entorno (le√≠da desde .env)
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
